Added lab 4
cyberg00se/java-labs pull request #1
Opened 2020-03-26 09:02 UTC by cyberg00se

Lab with classes of vehicles, passengers and road + unit tests of vehicles and road.

2020-03-26 09:05 UTC, cyberg00se commented
@SDiakov

2020-03-29 10:32 UTC, SDiakov requested changes

2020-03-29 10:32 UTC, SDiakov commented on lab4/src/Vehicle.java
> +            throw new Exception("all seats are occupied");
Додайте юніт тест на expected exception

2020-03-29 10:32 UTC, SDiakov commented on lab4/src/Vehicle.java
> +            throw new Exception("this passenger is not here");
Додайте юніт тест на expected exception

2020-03-29 15:41 UTC, cyberg00se commented on lab4/src/Vehicle.java
> +            throw new Exception("all seats are occupied");
Додала

2020-03-29 15:41 UTC, cyberg00se commented on lab4/src/Vehicle.java
> +            throw new Exception("this passenger is not here");
Додала

2020-03-29 15:53 UTC, SDiakov commented on lab4/src/VehicleExceptionTest.java
> +        catch (Exception e) {
Catch не потрібен. Використайте Assert Throws

2020-03-29 16:18 UTC, cyberg00se commented on lab4/src/VehicleExceptionTest.java
> +        catch (Exception e) {
Виконала

2020-04-05 12:31 UTC, SDiakov commented on lab4/src/VehicleExceptionTest.java
> +        Exception exception = assertThrows(Exception.class, () -> {
Зараховую. Але на майбутнє - краще за все створити власний клас-наслідник від Exception і перевіряти, що зявився саме його екземпляр. А не відловлювати усі Exception і потім звіряти текст.

2020-04-05 12:33 UTC, merged